name: hashicorp/null
resources:
    null_resource Resource - terraform-provider-null:
        subCategory: ""
        description: The null_resource resource implements the standard resource lifecycle but takes no further action. The triggers argument allows specifying an arbitrary set of values that, when changed, will cause the resource to be replaced.
        name: null_resource Resource - terraform-provider-null
        title: null_resource Resource - terraform-provider-null
        argumentDocs: {}
        importStatements: []
